######################################################################
# Automatically generated by qmake (3.0) Thu Oct 2 00:26:08 2014
######################################################################

TEMPLATE = app
TARGET = image_cap
INCLUDEPATH += .
INCLUDEPATH += /usr/local/include/opencv2
LIBS += -lopencv_core -lopencv_highgui -lopencv_imgproc

# Input
SOURCES += imcap.cpp
